"""Authoritative curriculum metadata for the JAX tutorial.

The lesson modules remain executable teaching artifacts; this registry captures the
student-facing curriculum contract used by notebooks, tests, and documentation.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class LessonSpec:
    number: int
    slug: str
    title: str
    phase: str
    module: str
    notebook: str
    solution: str
    exercise_name: str
    solution_function: str
    objectives: tuple[str, str, str]
    mental_model: str
    common_mistakes: tuple[str, str]
    exercise_prompt: str
    exercise_hint: str
    checkpoint: tuple[str, str, str]
    extension: str


LESSONS: tuple[LessonSpec, ...] = (
    LessonSpec(
        1,
        "why_jax",
        "Why JAX for Deep Learning",
        "Foundations",
        "lessons.lesson_01_why_jax",
        "notebooks/lesson_01_why_jax.ipynb",
        "solutions.lesson_01_solution",
        "exercise_accuracy_from_logits",
        "accuracy_from_logits",
        (
            "Train a tiny logistic model with pure functions and immutable parameter updates.",
            "Connect NumPy-shaped array code to JAX transformations and autodiff.",
            "Read a before/after loss check as evidence that a functional update worked.",
        ),
        "JAX code is ordinary array code until a transformation stages it. Keep model state explicit so `grad`, `jit`, and tests see the same inputs.",
        (
            "Treating parameter dictionaries like hidden mutable model state.",
            "Interpreting a decreasing loss without checking shapes, labels, and logits.",
        ),
        "Implement accuracy from binary logits by thresholding probabilities and averaging correct predictions.",
        "Use `jax.nn.sigmoid(logits) >= 0.5`, compare to labels, cast to float, then take the mean.",
        (
            "The final loss is lower than the initial loss after repeated gradient steps.",
            "Predictions have the same leading dimension as the labels.",
            "The exercise check reports an accuracy between 0 and 1.",
        ),
        "Try changing the learning rate to see when the simple training loop becomes unstable.",
    ),
    LessonSpec(
        2,
        "arrays",
        "JAX Arrays and Core Operations",
        "Foundations",
        "lessons.lesson_02_arrays",
        "notebooks/lesson_02_arrays.ipynb",
        "solutions.lesson_02_solution",
        "exercise_row_normalize",
        "row_normalize",
        (
            "Create and inspect JAX arrays with predictable shapes and dtypes.",
            "Use slicing, broadcasting, indexed updates, and matrix multiplication idiomatically.",
            "Normalize rows without mutating the input array.",
        ),
        "JAX arrays are immutable values. Operations return new arrays, which is what makes transformations and device placement predictable.",
        (
            "Expecting `x[index] = value` style mutation to work inside transformed code.",
            "Letting broadcasting hide an unintended rank or axis mismatch.",
        ),
        "Implement row normalization so each row sums to one while preserving shape.",
        "Compute row sums with `keepdims=True` and divide with a small zero-safety guard if needed.",
        (
            "Immutable updates leave the original input unchanged.",
            "Broadcasted operations have the expected matrix shape.",
            "Normalized row sums are close to one.",
        ),
        "Add a zero row and decide how your normalization should handle it.",
    ),
    LessonSpec(
        3,
        "gradients",
        "Automatic Differentiation with grad",
        "Foundations",
        "lessons.lesson_03_gradients",
        "notebooks/lesson_03_gradients.ipynb",
        "solutions.lesson_03_solution",
        "exercise_mae_grad",
        "mae_grads",
        (
            "Differentiate scalar-valued functions with `jax.grad`.",
            "Compute parameter gradients for a linear model loss.",
            "Inspect Jacobians when a function returns vectors instead of scalars.",
        ),
        "Reverse-mode autodiff needs a scalar objective. When outputs are structured, choose the derivative object deliberately: gradient, Jacobian, or Hessian.",
        (
            "Calling `grad` on a vector-valued function and expecting a full Jacobian.",
            "Differentiating through integer or boolean values instead of floating arrays.",
        ),
        "Implement MAE loss gradients for a linear model.",
        "Define an MAE scalar loss first, then pass it to `jax.grad` with respect to the parameter tree.",
        (
            "The scalar derivative matches the analytic slope at the demo point.",
            "Gradient pytrees match the parameter pytree structure.",
            "The MAE gradient exposes the sign-based behavior of absolute error.",
        ),
        "Compare MSE and MAE gradients near zero residuals.",
    ),
    LessonSpec(
        4,
        "jit",
        "Compilation with jit",
        "Foundations",
        "lessons.lesson_04_jit",
        "notebooks/lesson_04_jit.ipynb",
        "solutions.lesson_04_solution",
        "exercise_jitted_relu",
        "_relu",
        (
            "Compile pure numerical functions with `jax.jit`.",
            "Separate array inputs from static Python choices that affect tracing.",
            "Run a jitted training step that returns updated parameters and loss.",
        ),
        "`jit` traces Python once for a shape/dtype/static-argument signature, then reuses compiled device code for matching calls.",
        (
            "Changing Python control decisions inside a jitted function without marking them static.",
            "Expecting print/debug side effects to behave like eager Python during compilation.",
        ),
        "Implement a jitted ReLU and confirm it preserves shape while clipping negatives to zero.",
        "Write a small pure function around `jnp.maximum(x, 0)` and wrap it with `jax.jit`.",
        (
            "The jitted train step returns the same tree structure as the input parameters.",
            "Static choices such as `power` are explicit at the call boundary.",
            "The ReLU exercise output has no negative values.",
        ),
        "Use `jax.make_jaxpr` on a tiny function before and after adding a Python branch.",
    ),
    LessonSpec(
        5,
        "vmap",
        "Vectorization with vmap",
        "Transform Patterns",
        "lessons.lesson_05_vmap",
        "notebooks/lesson_05_vmap.ipynb",
        "solutions.lesson_05_solution",
        "exercise_batch_cosine_similarity",
        "batch_cosine_similarity",
        (
            "Lift a single-example function to batched inputs with `jax.vmap`.",
            "Control mapped axes for pairwise operations.",
            "Compare loop-style batching with transformation-style batching.",
        ),
        "`vmap` adds a batch axis to a function contract. The inner function should still describe one example clearly.",
        (
            "Mapping over the wrong axis and silently comparing unrelated examples.",
            "Writing a Python loop first and forgetting the simpler single-example function.",
        ),
        "Implement batched cosine similarity for aligned batches of vectors.",
        "Normalize each row by its L2 norm, multiply aligned rows, then sum over the feature axis.",
        (
            "Loop and `vmap` L2 computations agree numerically.",
            "Batched linear output keeps the batch dimension first.",
            "Cosine similarity returns one score per paired example.",
        ),
        "Nest `vmap` to build a full pairwise similarity matrix.",
    ),
    LessonSpec(
        6,
        "control_flow",
        "JAX Control Flow",
        "Transform Patterns",
        "lessons.lesson_06_control_flow",
        "notebooks/lesson_06_control_flow.ipynb",
        "solutions.lesson_06_solution",
        "exercise_weighted_cumsum",
        "weighted_cumsum",
        (
            "Use `lax.cond` for data-dependent branches.",
            "Use `lax.scan` for loop-carried state over sequences.",
            "Recognize when Python control flow should become JAX control flow.",
        ),
        "Transformed JAX code needs control flow that can be represented in the traced program rather than decided by Python at trace time.",
        (
            "Branching on a traced array with a Python `if`.",
            "Using a Python loop for sequence state that should compose with `jit` or gradients.",
        ),
        "Implement a weighted cumulative sum with `lax.scan`.",
        "Carry the running value and emit each updated carry as the scan output.",
        (
            "Safe inverse avoids division blowups around zero.",
            "Scan cumulative sums match the intuitive running total.",
            "Weighted cumulative sums preserve sequence length.",
        ),
        "Rewrite the scan as an explicit Python loop and compare where each version can be jitted.",
    ),
    LessonSpec(
        7,
        "randomness",
        "Random Numbers and PRNG Keys",
        "Transform Patterns",
        "lessons.lesson_07_randomness",
        "notebooks/lesson_07_randomness.ipynb",
        "solutions.lesson_07_solution",
        "exercise_gaussian_stats",
        "gaussian_stats",
        (
            "Create, split, and pass explicit PRNG keys.",
            "Sample deterministic random arrays for tests and demos.",
            "Apply dropout without hidden global RNG state.",
        ),
        "A JAX key is an explicit input, not a mutable global generator. Splitting keys creates independent streams you can pass through pure functions.",
        (
            "Reusing the same key and mistaking repeated samples for randomness.",
            "Hiding key creation inside model code where tests cannot control it.",
        ),
        "Sample `n` standard normal values and return their empirical mean and standard deviation.",
        "Use one key once, then compute `jnp.mean` and `jnp.std` over the sample.",
        (
            "Splitting one key yields reproducible but distinct samples.",
            "Dropout preserves shape and scales kept activations.",
            "Gaussian summary statistics are near the expected mean and scale.",
        ),
        "Thread a key through two stochastic operations without reusing it.",
    ),
    LessonSpec(
        8,
        "pytrees",
        "Pytrees Fundamentals",
        "Transform Patterns",
        "lessons.lesson_08_pytrees",
        "notebooks/lesson_08_pytrees.ipynb",
        "solutions.lesson_08_solution",
        "exercise_count_parameters",
        "count_parameters",
        (
            "Treat nested parameter containers as first-class JAX values.",
            "Map, scale, add, flatten, and rebuild parameter pytrees.",
            "Apply SGD updates to matching parameter and gradient structures.",
        ),
        "A pytree is the structure plus its array leaves. JAX transformations preserve and reason about both pieces.",
        (
            "Updating only one leaf while forgetting the rest of the tree.",
            "Flattening a tree and losing the treedef needed to rebuild it.",
        ),
        "Count the total scalar parameters across every array leaf in a pytree.",
        "Use `jax.tree_util.tree_leaves` and sum each leaf's `.size`.",
        (
            "Tree arithmetic preserves the nested parameter structure.",
            "Flattening plus unflattening round-trips the original tree.",
            "Parameter counts equal the sum of every leaf size.",
        ),
        "Add a bias-only subtree and verify that the counting function does not assume layer names.",
    ),
    LessonSpec(
        9,
        "linear_models",
        "Linear Models from Scratch",
        "Training Foundations",
        "lessons.lesson_09_linear_models",
        "notebooks/lesson_09_linear_models.ipynb",
        "solutions.lesson_09_solution",
        "exercise_mae_loss",
        "mae_loss",
        (
            "Build a deterministic linear regression dataset.",
            "Train a linear model with explicit parameters and gradients.",
            "Compare MSE and MAE as scalar training objectives.",
        ),
        "A model can be just a pure function plus an explicit parameter pytree. Frameworks add ergonomics, not magic.",
        (
            "Mixing data generation, model evaluation, and optimization into one opaque function.",
            "Changing loss definitions without checking their gradient behavior.",
        ),
        "Implement MAE loss for the linear model predictions.",
        "Take `jnp.mean(jnp.abs(linear_forward(params, x) - y))`.",
        (
            "Training loss decreases over repeated gradient steps.",
            "Learned parameters produce predictions with the target shape.",
            "MAE is non-negative and shares the batch axis with MSE examples.",
        ),
        "Swap the optimizer from plain gradient descent to momentum after lesson 10.",
    ),
    LessonSpec(
        10,
        "optimization",
        "Optimization Basics",
        "Training Foundations",
        "lessons.lesson_10_optimization",
        "notebooks/lesson_10_optimization.ipynb",
        "solutions.lesson_10_solution",
        "exercise_adaptive_lr",
        "adaptive_lr",
        (
            "Minimize a convex quadratic with gradient descent.",
            "Track optimizer state for momentum updates.",
            "Schedule learning rates as explicit functions of step number.",
        ),
        "Optimizers are state machines over parameters and auxiliary state. Keeping both explicit makes them easy to test and replace.",
        (
            "Treating momentum velocity as hidden mutable state.",
            "Judging an optimizer without plotting or inspecting the loss trajectory.",
        ),
        "Implement a simple adaptive learning-rate schedule.",
        "Return a decayed version of `base_lr` as `step` increases.",
        (
            "Gradient descent and momentum both move the parameter toward the quadratic minimum.",
            "Momentum carries velocity between steps.",
            "The adaptive learning rate remains positive and decreases over time.",
        ),
        "Try a too-large learning rate and inspect whether momentum helps or hurts.",
    ),
    LessonSpec(
        11,
        "minibatching",
        "Mini-Batching and Data Pipelines",
        "Training Foundations",
        "lessons.lesson_11_minibatching",
        "notebooks/lesson_11_minibatching.ipynb",
        "solutions.lesson_11_solution",
        "exercise_epoch_mean_loss",
        "epoch_mean_loss",
        (
            "Create deterministic toy classification data.",
            "Slice and shuffle mini-batches with explicit keys and indices.",
            "Aggregate per-batch losses into epoch-level metrics.",
        ),
        "Mini-batching is bookkeeping around arrays. Make indices, shuffling, and aggregation explicit so training remains reproducible.",
        (
            "Dropping or duplicating examples when the final batch is smaller.",
            "Shuffling inputs and labels with different permutations.",
        ),
        "Compute the mean loss across all batches in an epoch.",
        "Convert the sequence to a JAX array and call `jnp.mean`.",
        (
            "Batch indices cover the dataset in predictable chunks.",
            "Shuffled features and labels stay aligned.",
            "Epoch mean loss is a scalar summary of batch losses.",
        ),
        "Add a `drop_last` option and test how it changes the number of batches.",
    ),
    LessonSpec(
        12,
        "losses_stability",
        "Loss Functions and Numerical Stability",
        "Training Foundations",
        "lessons.lesson_12_losses_stability",
        "notebooks/lesson_12_losses_stability.ipynb",
        "solutions.lesson_12_solution",
        "exercise_label_smoothing",
        "label_smoothing",
        (
            "Identify unstable probability-space loss calculations.",
            "Use logits-space cross entropy and stable softmax patterns.",
            "Apply label smoothing without changing batch or class axes.",
        ),
        "Stable losses avoid forming extreme probabilities too early. Prefer logits and log-sum-exp based primitives when possible.",
        (
            "Taking `log` of probabilities that may be exactly zero.",
            "Smoothing labels in a way that changes each row's probability mass.",
        ),
        "Implement label smoothing for one-hot class targets.",
        "Blend each one-hot row with a uniform distribution over classes.",
        (
            "Stable softmax remains finite for large logits.",
            "Logits-space cross entropy returns finite scalar losses.",
            "Smoothed label rows still sum to one.",
        ),
        "Compare gradients from probability-space and logits-space losses on extreme logits.",
    ),
    LessonSpec(
        13,
        "higher_order",
        "Higher-Order Autodiff",
        "Advanced Single-Device JAX",
        "lessons.lesson_13_higher_order",
        "notebooks/lesson_13_higher_order.ipynb",
        "solutions.lesson_13_solution",
        "exercise_directional_derivative",
        "directional_derivative",
        (
            "Compose autodiff transforms for first and second derivatives.",
            "Compute Jacobians and Hessians for small examples.",
            "Use directional derivatives to ask local sensitivity questions.",
        ),
        "Higher-order derivatives are transformations of transformations. Keep functions small and scalar/vector contracts explicit.",
        (
            "Building a Hessian for a large model when a vector product would answer the question.",
            "Forgetting that higher-order derivatives amplify numerical and shape mistakes.",
        ),
        "Compute the directional derivative of a scalar function at a point.",
        "Take `jnp.vdot(jax.grad(f)(x), direction)` for a scalar-valued function `f`.",
        (
            "First and second derivatives match the scalar example.",
            "Jacobian and Hessian shapes match input/output dimensions.",
            "Directional derivatives return scalar sensitivity values.",
        ),
        "Replace the explicit Hessian with Hessian-vector products for larger vectors.",
    ),
    LessonSpec(
        14,
        "debugging_profiling",
        "Debugging and Profiling JAX Programs",
        "Advanced Single-Device JAX",
        "lessons.lesson_14_debugging_profiling",
        "notebooks/lesson_14_debugging_profiling.ipynb",
        "solutions.lesson_14_solution",
        "exercise_count_nans",
        "count_nans",
        (
            "Inspect traced programs with JAXPR.",
            "Time eager and jitted functions without trusting the first compile call.",
            "Detect NaNs and validate gradients with finite differences.",
        ),
        "Debugging JAX often means separating compile-time tracing from runtime execution. Inspect the staged program and synchronize before timing.",
        (
            "Timing a jitted function without accounting for asynchronous dispatch or compilation.",
            "Looking for Python side effects instead of inspecting arrays and JAXPR.",
        ),
        "Count NaN values in an array.",
        "Use `jnp.isnan(x)` and sum the boolean mask.",
        (
            "The JAXPR contains primitive operations rather than Python source lines.",
            "NaN checks identify exactly the invalid entries.",
            "Finite-difference gradients are close to autodiff for smooth scalar examples.",
        ),
        "Add `jax.debug.print` to a tiny jitted function and observe when it emits output.",
    ),
    LessonSpec(
        15,
        "flax_intro",
        "Intro to Flax Modules",
        "Neural Network Stack",
        "lessons.lesson_15_flax_intro",
        "notebooks/lesson_15_flax_intro.ipynb",
        "solutions.lesson_15_solution",
        "exercise_parameter_count",
        "parameter_count",
        (
            "Define a compact Flax module for a small MLP.",
            "Initialize and apply model parameters explicitly.",
            "Measure loss without hiding params inside the module object.",
        ),
        "Flax modules describe computation; variables hold state. Initialization creates the parameter pytree that later calls consume.",
        (
            "Calling a Flax module before initializing variables.",
            "Assuming module instances own trained parameters like mutable objects.",
        ),
        "Count scalar parameters in the initialized Flax parameter pytree.",
        "Reuse the pytree leaf counting pattern from lesson 8.",
        (
            "Initialized parameter collections contain a `params` tree.",
            "Model outputs have batch dimension and output dimension.",
            "Parameter count is positive and matches the tree leaves.",
        ),
        "Change hidden width and watch the parameter count scale.",
    ),
    LessonSpec(
        16,
        "flax_optax_training",
        "Training Loops with Flax and Optax",
        "Neural Network Stack",
        "lessons.lesson_16_flax_optax_training",
        "notebooks/lesson_16_flax_optax_training.ipynb",
        "solutions.lesson_16_solution",
        "exercise_classification_accuracy",
        "classification_accuracy",
        (
            "Create a Flax `TrainState` with model params and an Optax optimizer.",
            "Write a jitted train step that updates state functionally.",
            "Track loss and accuracy for a tiny classifier.",
        ),
        "Flax owns the model definition, Optax owns optimizer transformations, and `TrainState` carries the explicit mutable-looking state as immutable values.",
        (
            "Forgetting to pass `apply_fn` and params through the loss function explicitly.",
            "Updating parameters without carrying optimizer state forward.",
        ),
        "Compute classification accuracy from logits and integer labels.",
        "Use `jnp.argmax(logits, axis=-1)` and average equality with labels.",
        (
            "Training loss decreases on the toy dataset.",
            "The state step increments as training progresses.",
            "Accuracy is a scalar in the range [0, 1].",
        ),
        "Swap Adam for SGD and compare the first 20 losses.",
    ),
    LessonSpec(
        17,
        "regularization_eval",
        "Regularization and Model Evaluation",
        "Neural Network Stack",
        "lessons.lesson_17_regularization_eval",
        "notebooks/lesson_17_regularization_eval.ipynb",
        "solutions.lesson_17_solution",
        "exercise_f1_score",
        "f1_score",
        (
            "Add L2 regularization to a binary classifier loss.",
            "Compute accuracy, precision, and recall from logits.",
            "Interpret F1 as a balance between precision and recall.",
        ),
        "Evaluation metrics are array programs too. Make thresholds and reductions explicit so they can be tested and transformed.",
        (
            "Reporting accuracy alone on imbalanced classification examples.",
            "Dividing by zero when no positive predictions or labels are present.",
        ),
        "Compute F1 from precision and recall with zero-safe denominator handling.",
        "Use `2 * precision * recall / max(precision + recall, eps)`.",
        (
            "Regularized loss is at least as large as the data loss when weight decay is positive.",
            "Precision and recall are bounded scalar metrics.",
            "F1 is zero-safe and bounded between 0 and 1.",
        ),
        "Sweep classification thresholds and compare precision/recall tradeoffs.",
    ),
    LessonSpec(
        18,
        "sequence_scan",
        "Sequence Models with lax.scan",
        "Neural Network Stack",
        "lessons.lesson_18_sequence_scan",
        "notebooks/lesson_18_sequence_scan.ipynb",
        "solutions.lesson_18_solution",
        "exercise_reverse_scan",
        "reverse_scan_suffix_sum",
        (
            "Represent recurrent state updates as scan bodies.",
            "Run a simple RNN over a sequence with explicit carry state.",
            "Compute sequence losses with shape checks.",
        ),
        "A recurrent model is a scan: carry the hidden state, emit outputs, and keep sequence axes explicit.",
        (
            "Mixing batch and time axes without naming the convention.",
            "Closing over mutable hidden state instead of carrying it through scan.",
        ),
        "Compute reverse suffix sums with `lax.scan` running backward.",
        "Use `reverse=True` and emit the updated carry at each step.",
        (
            "Scan cumulative sums match simple examples.",
            "RNN outputs keep one output per time step.",
            "Reverse scan results align with suffix-sum intuition.",
        ),
        "Add a batch axis and use `vmap` around the scanned sequence function.",
    ),
    LessonSpec(
        19,
        "pmap_parallel",
        "Parallelization with pmap",
        "Scaling and Systems",
        "lessons.lesson_19_pmap_parallel",
        "notebooks/lesson_19_pmap_parallel.ipynb",
        "solutions.lesson_19_solution",
        "exercise_data_parallel_sum",
        "data_parallel_sum",
        (
            "Inspect local devices before choosing a parallel strategy.",
            "Reshape data for device-major `pmap` inputs.",
            "Distinguish single-device fallbacks from true cross-device collectives.",
        ),
        "`pmap` maps one function over local devices. On a single device, collective operations are mathematically valid but do not demonstrate distributed communication.",
        (
            "Mistaking a single-device fallback for evidence of scaling behavior.",
            "Forgetting that `pmap` expects a leading axis sized by local device count.",
        ),
        "Implement a data-parallel sum using `lax.psum`, with a clear single-device fallback.",
        "Inside `pmap`, use `lax.psum(value, axis_name='d')`; outside it, return the ordinary sum for CPU-only demos.",
        (
            "The notebook reports the number of local devices before parallel examples.",
            "Reshaped arrays have leading axis equal to local device count.",
            "Single-device output is labeled as a fallback, not a scaling result.",
        ),
        "Run with simulated CPU devices and compare the collective output shape.",
    ),
    LessonSpec(
        20,
        "pjit_partitioning",
        "Partitioning and pjit Concepts",
        "Scaling and Systems",
        "lessons.lesson_20_pjit_partitioning",
        "notebooks/lesson_20_pjit_partitioning.ipynb",
        "solutions.lesson_20_solution",
        "exercise_make_sharded_array",
        "make_sharded_array",
        (
            "Build a named device mesh for partitioning examples.",
            "Attach replicated and first-dimension shardings to arrays.",
            "Understand single-device partitioning as placement metadata rather than speedup.",
        ),
        "Named sharding describes how logical array axes map to a device mesh. The same API can be demonstrated on one device, but partitioning is only visible with multiple devices.",
        (
            "Equating `NamedSharding` metadata with actual multi-device parallelism on one device.",
            "Using mesh contexts mechanically without explaining which calls need them.",
        ),
        "Place an array on a named sharding and return the resulting JAX array.",
        "Create a mesh, choose `NamedSharding(mesh, P('data', None))`, then call `jax.device_put`.",
        (
            "Matrix multiplication returns the same numerical result as ordinary `x @ w`.",
            "Sharding inspection returns a real sharding object.",
            "The notebook states whether the current run is single-device or multi-device.",
        ),
        "Try the same lesson with forced multiple CPU devices before importing JAX.",
    ),
    LessonSpec(
        21,
        "tensor_sharding",
        "Tensor Sharding with Named Axes",
        "Scaling and Systems",
        "lessons.lesson_21_tensor_sharding",
        "notebooks/lesson_21_tensor_sharding.ipynb",
        "solutions.lesson_21_solution",
        "exercise_verify_sharding_name",
        "verify_named_sharding",
        (
            "Place arrays with replicated and data-axis shardings.",
            "Inspect sharding metadata after device placement.",
            "Run linear algebra while preserving placement semantics.",
        ),
        "Sharding is part of an array's placement contract. Correct code should make the intended axis names visible and testable.",
        (
            "Assuming sharding is visible from array values alone.",
            "Forgetting to verify axis names when teaching partitioned tensor layouts.",
        ),
        "Verify that an array's sharding contains the expected named mesh axis.",
        "Inspect `x.sharding` and look for the axis name in its spec or string representation.",
        (
            "Placed arrays report sharding metadata.",
            "Single-device examples still preserve named-axis intent.",
            "The verification exercise returns a boolean-style result.",
        ),
        "Extend the mesh to include a model axis on hardware that supports it.",
    ),
    LessonSpec(
        22,
        "checkpointing_experiments",
        "Checkpointing and Experiment Management",
        "Production Workflow",
        "lessons.lesson_22_checkpointing_experiments",
        "notebooks/lesson_22_checkpointing_experiments.ipynb",
        "solutions.lesson_22_solution",
        "exercise_best_run",
        "best_run",
        (
            "Record run metadata in plain serializable structures.",
            "Save and restore small parameter pytrees.",
            "Keep notebook-generated artifacts out of tracked repository files.",
        ),
        "Experiment state is useful only when it can be restored and compared. Keep metadata explicit and write demos to temporary paths.",
        (
            "Writing notebook demo outputs over tracked files.",
            "Saving parameters without enough metadata to reproduce the run.",
        ),
        "Select the best run metadata entry by validation loss.",
        "Use `min(runs, key=lambda run: run['validation_loss'])` or an equivalent explicit comparison.",
        (
            "Metadata round-trips through JSON without changing fields.",
            "Checkpointed parameter leaves restore with matching values.",
            "Notebook execution writes only to a temporary directory.",
        ),
        "Add git commit hash or dependency versions to the metadata dictionary.",
    ),
    LessonSpec(
        23,
        "jax_ecosystem",
        "JAX Ecosystem Tour",
        "Production Workflow",
        "lessons.lesson_23_jax_ecosystem",
        "notebooks/lesson_23_jax_ecosystem.ipynb",
        "solutions.lesson_23_solution",
        "exercise_is_loss_decreasing",
        "is_loss_decreasing",
        (
            "Identify where core JAX ends and ecosystem libraries begin.",
            "Run one Optax optimizer update by hand.",
            "Use trend checks to validate training logs.",
        ),
        "JAX is the transformation and array substrate; libraries such as Flax and Optax package common modeling and optimization patterns on top.",
        (
            "Treating ecosystem libraries as replacements for understanding JAX transformations.",
            "Checking only the final loss without validating the trajectory direction.",
        ),
        "Return whether a sequence of losses is decreasing from first to last.",
        "Compare the last loss to the first loss and return a boolean scalar/value.",
        (
            "The ecosystem summary names the role of each library.",
            "An Optax update changes parameters and optimizer state.",
            "Loss trend checks catch non-improving runs.",
        ),
        "Add a short note about a library you would use for data loading, serving, or checkpointing.",
    ),
    LessonSpec(
        24,
        "capstone",
        "End-to-End Capstone Project",
        "Production Workflow",
        "lessons.lesson_24_capstone",
        "notebooks/lesson_24_capstone.ipynb",
        "solutions.lesson_24_solution",
        "exercise_confusion_matrix",
        "confusion_matrix",
        (
            "Train a compact Flax classifier end to end on deterministic toy data.",
            "Save, restore, evaluate, and report model behavior with vectorized metrics.",
            "Tie together PRNGs, pytrees, losses, Optax state, and evaluation checks.",
        ),
        "A JAX project is a set of explicit state transitions: data to params, params to loss, optimizer state to new state, and predictions to metrics.",
        (
            "Ending with imperative metric code that cannot compose with JAX transformations.",
            "Reporting accuracy without inspecting confusion matrix counts.",
        ),
        "Build a vectorized confusion matrix from predicted and true labels.",
        "Start with zeros and use `mat.at[labels, preds].add(1)` over whole arrays, or use a `bincount` formulation.",
        (
            "Training improves loss and reaches high accuracy on XOR.",
            "Saved and restored parameters preserve the trained tree structure.",
            "Confusion matrix counts sum to the number of evaluated examples.",
        ),
        "Swap XOR for a slightly larger synthetic classification dataset and update the report.",
    ),
    LessonSpec(
        25,
        "transform_composition",
        "Transform Composition Patterns",
        "Integration Labs",
        "lessons.lesson_25_transform_composition",
        "notebooks/lesson_25_transform_composition.ipynb",
        "solutions.lesson_25_solution",
        "exercise_clip_gradients",
        "clip_gradients",
        (
            "Compose `vmap`, `grad`, and `jit` without changing the mathematical contract.",
            "Compare per-example gradients with gradients of a reduced batch objective.",
            "Use a compiled update as an integration point for earlier transform lessons.",
        ),
        "Transform composition works best when each function has a crisp contract: one example, one batch, one loss, or one update.",
        (
            "Changing the reduction axis and accidentally changing what the gradient means.",
            "Compiling a large opaque training step before checking the small eager pieces.",
        ),
        "Clip a gradient pytree by global L2 norm while preserving its structure.",
        "Compute the global norm from all leaves, form a scale no larger than one, then tree-map the scale over the leaves.",
        (
            "Per-example gradient leaves keep the batch dimension first.",
            "The compiled update returns the same parameter tree keys as the input.",
            "Clipped gradients have global norm no larger than the requested limit.",
        ),
        "Swap the order of `jit`, `vmap`, and `grad` for a tiny function and inspect the resulting JAXPR.",
    ),
    LessonSpec(
        26,
        "performance_memory",
        "Performance and Memory Measurement",
        "Integration Labs",
        "lessons.lesson_26_performance_memory",
        "notebooks/lesson_26_performance_memory.ipynb",
        "solutions.lesson_26_solution",
        "exercise_estimate_batch_bytes",
        "estimate_batch_bytes",
        (
            "Measure compiled work only after synchronizing asynchronous JAX execution.",
            "Separate compilation cost from repeated execution cost in small benchmarks.",
            "Estimate memory use from pytree leaves and batch shapes.",
        ),
        "JAX dispatch is asynchronous, so timing without `block_until_ready` often measures enqueue time rather than compute time.",
        (
            "Timing the first jitted call and treating compilation as steady-state performance.",
            "Ignoring activation and batch memory when choosing model or batch size.",
        ),
        "Estimate dense tensor memory from a batch shape and dtype byte width.",
        "Multiply every dimension in the shape by the dtype size in bytes.",
        (
            "Jitted and eager matrix-stack outputs have the same shape.",
            "Blocking runs produce a numeric result and elapsed time.",
            "Estimated batch bytes equal the product of shape dimensions times dtype size.",
        ),
        "Benchmark a second call separately and compare it with the first compile-plus-run call.",
    ),
    LessonSpec(
        27,
        "data_input_pipelines",
        "Data Input Pipelines",
        "Integration Labs",
        "lessons.lesson_27_data_input_pipelines",
        "notebooks/lesson_27_data_input_pipelines.ipynb",
        "solutions.lesson_27_solution",
        "exercise_pad_to_batch",
        "pad_to_batch",
        (
            "Split deterministic records into train and validation partitions.",
            "Create mini-batch slices without losing feature-label alignment.",
            "Standardize evaluation data using statistics from the training split only.",
        ),
        "Input pipelines are part of the model contract: shapes, ordering, padding, and normalization choices decide what the compiled step receives.",
        (
            "Computing normalization statistics on validation or test examples.",
            "Letting a short final batch break a compiled step that expects fixed shapes.",
        ),
        "Pad an array along the leading axis so its length is divisible by the batch size.",
        "Compute the remainder, add only the needed rows, and leave trailing axes unchanged.",
        (
            "Train and validation splits preserve matching feature and label counts.",
            "Mini-batch iteration covers examples predictably with or without dropping the last batch.",
            "Padded batches have a leading axis divisible by the target batch size.",
        ),
        "Add a mask alongside padded examples so losses can ignore synthetic rows.",
    ),
    LessonSpec(
        28,
        "multidevice_readiness",
        "Multi-Device Readiness Checks",
        "Integration Labs",
        "lessons.lesson_28_multidevice_readiness",
        "notebooks/lesson_28_multidevice_readiness.ipynb",
        "solutions.lesson_28_solution",
        "exercise_validate_global_batch_size",
        "validate_global_batch_size",
        (
            "Report device inventory before selecting a parallel execution strategy.",
            "Validate global batch sizes for per-device splitting.",
            "Label single-device fallback behavior separately from collective execution.",
        ),
        "Production multi-device code starts with readiness checks: device count, global batch divisibility, and explicit fallback behavior.",
        (
            "Assuming a notebook is using collectives just because it imports `pmap` concepts.",
            "Choosing a global batch size that cannot be split evenly across devices.",
        ),
        "Return whether a global batch size can be split evenly across the selected devices.",
        "Require a positive device count, at least one example per device, and exact divisibility.",
        (
            "Device inventory reports backend and local device count.",
            "Reshaped global batches expose a device-major leading axis.",
            "Invalid batch/device combinations are rejected before parallel code runs.",
        ),
        "Run the lesson in a fresh process with simulated CPU devices and compare the readiness report.",
    ),
    LessonSpec(
        29,
        "experiment_analysis",
        "Experiment Analysis and Comparison",
        "Integration Labs",
        "lessons.lesson_29_experiment_analysis",
        "notebooks/lesson_29_experiment_analysis.ipynb",
        "solutions.lesson_29_solution",
        "exercise_select_pareto_runs",
        "select_pareto_runs",
        (
            "Rank experiment runs by validation loss and runtime.",
            "Attach environment metadata to make comparisons reproducible.",
            "Identify Pareto-efficient runs when accuracy and cost trade off.",
        ),
        "Experiment analysis turns run metadata into decisions. Keep metrics and costs explicit so ranking rules can be reviewed.",
        (
            "Choosing the lowest loss without checking whether the runtime cost is acceptable.",
            "Comparing runs without recording package or environment context.",
        ),
        "Select runs that are not dominated on both validation loss and runtime.",
        "A run is dominated if another run is no worse on both metrics and strictly better on at least one.",
        (
            "The best run by validation loss is easy to identify from ranked metadata.",
            "Environment fields are copied into the run summary without changing metric values.",
            "Pareto selection keeps only runs that preserve a useful loss/runtime tradeoff.",
        ),
        "Add confidence intervals or repeated-seed aggregation to the run comparison.",
    ),
    LessonSpec(
        30,
        "deployment_model_cards",
        "Deployment Checks and Model Cards",
        "Integration Labs",
        "lessons.lesson_30_deployment_model_cards",
        "notebooks/lesson_30_deployment_model_cards.ipynb",
        "solutions.lesson_30_solution",
        "exercise_apply_threshold",
        "apply_threshold",
        (
            "Convert model scores into reviewable prediction records.",
            "Summarize calibration bins for simple deployment checks.",
            "Package metrics and limitations into a lightweight model card.",
        ),
        "Deployment is another transformation boundary: numeric outputs become decisions, reports, and operational constraints.",
        (
            "Shipping a threshold without documenting how it changes precision and recall.",
            "Reporting metrics without limitations or intended-use context.",
        ),
        "Convert probabilities into integer predictions using a configurable threshold.",
        "Compare probabilities with the threshold and cast the boolean mask to integer labels.",
        (
            "Prediction tables preserve IDs, scores, and thresholded decisions.",
            "Calibration bins report counts, confidence, and accuracy per range.",
            "Model cards contain metrics and limitations in serializable fields.",
        ),
        "Evaluate two thresholds and describe which deployment risk each threshold changes.",
    ),
)


def lesson_numbers() -> list[int]:
    return [lesson.number for lesson in LESSONS]


def get_lesson(number: int) -> LessonSpec:
    for lesson in LESSONS:
        if lesson.number == number:
            return lesson
    raise KeyError(f"Unknown lesson number: {number}")
